services:
  backend:
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile.prod
    image: brithe00/server
    env_file: .env
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    #build:
    #  context: ./frontend
    #  dockerfile: Dockerfile.prod
    image: brithe00/client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=/graphql
    depends_on:
      db:
        condition: service_healthy

  images-upload:
    #build:
    #  context: ./images-upload
    #  dockerfile: Dockerfile.prod
    image: brithe00/images-upload
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - images-upload
      - db

volumes:
  pgdata:
  uploads_data:
  redis_data:
