services:
  backend:
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile.prod
    image: brithe00/godrive-server
    env_file: .env
    ports:
      - 4001:4000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    #build:
    #  context: ./frontend
    #  dockerfile: Dockerfile.prod
    image: brithe00/godrive-client
    ports:
      - 3001:3000
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=/graphql
    depends_on:
      db:
        condition: service_healthy

  images-upload:
    #build:
    #  context: ./images-upload
    #  dockerfile: Dockerfile.prod
    image: brithe00/godrive-images-upload
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx
    ports:
      - "${NGINX_PORT:-7001}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
      - images-upload
      - db

volumes:
  pgdata:
  uploads_data:
  redis_data:

networks:
  default:
    name: staging_network
    driver: bridge
