services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=/graphql

  images-upload:
    build:
      context: ./images-upload
      dockerfile: Dockerfile.prod
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis_data:/data

  nginx:
    image: nginx
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:
  uploads_data:
  redis_data:
