name: 🧪 Frontend Tests

on:
  pull_request:

jobs:
  test-frontend:
    name: 🚀 Run Fronted Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: 📥 Check out code
        uses: actions/checkout@v2

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm run test
