name: 🧪 Backend Tests

on:
  pull_request:

jobs:
  test-backend:
    name: 🚀 Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out code
        uses: actions/checkout@v2

      - name: 📂 Navigate to backend
        run: cd backend

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm run test
